(defun Yaz()
  	(setq uretilensayi (+ 10 (random 89)))
	(defun getUretilenSayi()
		(block nil (return uretilensayi)))	
	(setf xyz (make-array '(99 3)))
	(defun getXYZ()
		(block nil (return xyz)))
	(loop for i from 0 to uretilensayi do
		(setf (aref xyz i 0) (+ 500 (random 499)))
		(setf (aref xyz i 1) (+ 1000 (random 499)))
		(setf (aref xyz i 2) (+ 1 (random 5)))
	)
)

(defun XYGir(taban tavan)
	(setq sayi (read))
	(block nil
		(if (>= sayi taban)
			(if (<= sayi tavan) (return sayi))
		)
		(print "Aralık Dışı Değer Girdiniz. Tekrar Giriş Yapınız: ")
		(XYGir taban tavan)
	)
)

(defun Oku()
	(Yaz)
	(setf xyz (getXYZ))
	(setq xi 0 yi 0 xyeni 0 yyeni 0)
	(setf farkhesabi (make-array '(99 2)))
	(defun getFarkHesabi()
		(block nil (return farkhesabi)))
	(print "XYeni Değeri 500-999: ")
	(setq xyeni (XYGir 500 999))
	(print "YYeni Değeri 1000-1499: ")
	(setq xyeni (XYGir 1000 1499))
	(loop for i from 0 to (getUretilenSayi) do
		(setq xi (- (aref xyz i 0) xyeni))
		(setq yi (- (aref xyz i 1) yyeni))
		(setf (aref farkhesabi i 0) (truncate (sqrt (+ xi yi))))
		(setf (aref farkhesabi i 1) (aref xyz i 2))
	)
)
(defun KBveTekrarSirala(dongu farktekrar)
	(setf gecici (make-array '(1 2)))
	(loop for i from 0 to dongu do
		(loop for j from (+ i 1) to dongu do
			(setq x (aref farktekrar j 0))
			(setq y (aref farktekrar i 0))
			(if (< x y)
				(setf (aref gecici 0 0) (aref farktekrar i 0)) )
			(if (< x y)
				(setf (aref gecici 0 1) (aref farktekrar i 1)) )
			(if (< x y)
				(setf (aref farktekrar i 0) (aref farktekrar j 0)) )
			(if (< x y)
				(setf (aref farktekrar i 1) (aref farktekrar j 1)) )
			(if (< x y)
				(setf (aref farktekrar j 0) (aref gecici 0 0)) )
			(if (< x y)
				(setf (aref farktekrar j 1) (aref gecici 0 1))
			)
		)
	)
	(block nil (return farktekrar))
)

(defun Sirala()
	(Oku)
	(setf tekrar (make-array '(5 2)))
	(defun getTekrar()
		(block nil (return tekrar)))
	(setf farkhesabi (KBveTekrarSirala (getUretilenSayi) (getFarkHesabi)))
	(setf q 0 w 0 e 0 r 0 y 0)
	(loop for i from 0 to 10 do
		(if (= 1 (aref farkhesabi i 1))
			(incf q))
		(if (= 2 (aref farkhesabi i 1))
			(incf w))
		(if (= 3 (aref farkhesabi i 1))
			(incf e))
		(if (= 4 (aref farkhesabi i 1))
			(incf r))
		(if (= 5 (aref farkhesabi i 1))
			(incf y))
	)
	(setf (aref tekrar 0 0) q)
	(setf (aref tekrar 0 1) 1)
	(setf (aref tekrar 1 0) w)
	(setf (aref tekrar 1 1) 2)
	(setf (aref tekrar 2 0) e)
	(setf (aref tekrar 2 1) 3)
	(setf (aref tekrar 3 0) r)
	(setf (aref tekrar 3 1) 4)
	(setf (aref tekrar 4 0) y)
	(setf (aref tekrar 4 1) 5)
	(setf tekrar (KBveTekrarSirala 4 (getTekrar)))
	(print "En Fazla Tekrar Eden S Sayısı: ")
	(print (aref tekrar 4 1))
)